#!/system/bin/sh

# Script to launch frandom at boot by Ryuinferno @ XDA

if [ -c "$FRANDOM" ]; then
  mv /dev/random /dev/random.ori
  ln -s /dev/frandom /dev/random
fi

if [ -c "$ERANDOM" ]; then
  mv /dev/urandom /dev/urandom.ori
  ln -s /dev/erandom /dev/urandom
fi
