#!/system/bin/sh

# block tweaks
for i in /sys/block/*/queue ; do
    echo 0 > $i/iostats
    echo 0 > $i/rotational
done

echo 0 > /sys/block/mmcblk0/queue/add_random
echo 2 > /sys/block/mmcblk0/queue/rq_affinity

# Default Read Ahead value for sdcard
echo 512 > /sys/block/mmcblk1/queue/read_ahead_kb

# adjust ext4 inode readahead
for partition in /sys/fs/ext4/mmcblk0p1* ; do
    echo 64 > $partition/inode_readahead_blks
done

# adjust f2fs ram threshold
if [ -e /sys/fs/f2fs ] ; then
    echo 20 > /sys/fs/f2fs/mmcblk0p14/ram_thresh
    echo 20 > /sys/fs/f2fs/mmcblk0p20/ram_thresh
fi

# enable and setup UKSM
echo 1 > /sys/kernel/mm/uksm/run
echo quiet > /sys/kernel/mm/uksm/cpu_governor
echo 10 > /sys/kernel/mm/uksm/max_cpu_percentage
echo 500 > /sys/kernel/mm/uksm/sleep_millisecs
